### ISSUE TITLE
Node-REDのセキュリティ対策を検討・調査する

### ISSUE THREAD

**Issue by sear-azazel** [m1kyusyu2016/m1kyusyu2016#12]
Node-REDにID/Passwordを設定できるか調査する

**Comment by m1kyusyu2016** [comment]
調査完了したら、#13 でアプリに反映する

**Comment by sear-azazel** [comment]
http://qiita.com/zuhito/items/dc44bf964f58bdd44c4b
ここを参考に、`package.json`と`bluemix-settings.js`を修正すればできると思います。
