### ISSUE TITLE
Node-REDフローをテキスト形式で管理する仕組みを確立する

### ISSUE THREAD

**Issue by sear-azazel** [m1kyusyu2016/m1kyusyu2016#17]
#16 を参考に

1. フローの書き出し
2. ファイル出力
3. リポジトリにcommit/push
4. フローの読み込み

を行う。

**Comment by ando-takashi** [comment]
お疲れ様です。安藤です。
上記テキストベースの課題について完了したため、
簡単な手順書を添付致します。
ご確認頂ければと思います。
[test_0410.xlsx](https://github.com/m1kyusyu2016/m1kyusyu2016/files/910063/test_0410.xlsx)

**Comment by sear-azazel** [comment]
確認したのでクローズします。
